version: "3.8"

services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ./data:/var/opt/memos
    expose:
      - 5230
    restart: always

volumes:
  caddy_data:
  caddy_config: